// config.js
window.API_BASE = '../../database/';

// Opcional: rutas específicas
window.ENDPOINTS = {
  obtenerFichaPorNumero: 'obtenerFichaPorNumero.php',
  obtenerFichaPorNumeroYPorId: 'obtenerFichaPorNumeroYPorId.php',
  obtenerSectores: 'obtenerSectores.php',
  obtenerManzanas: 'obtenerManzanas.php',
  obtenerTipoEdificaciones: 'obtenerTipoEdificaciones.php',
  obtenerTipoInteriores: 'obtenerTipoInteriores.php',
  obtenerHabilitacionesUrbanas: 'obtenerHabilitacionesUrbanas.php',
  obtenerVias: 'obtenerVias.php',
  obtenerUsosPorDescripcion: 'obtenerUsosPorDescripcion.php',
  obtenerUsosPorCodigo: 'obtenerUsosPorCodigo.php',
  obtenerClasificacionesPredios: 'obtenerClasificacionesPredios.php',
  obtenerPrediosCatastrales: 'obtenerPrediosCatastrales.php',
  obtenerTipoMateriales: 'obtenerTipoMateriales.php',
  obtenerTipoCategorias: 'obtenerTipoCategorias.php',
  obtenerCodigosInstalaciones: 'obtenerCodigosInstalaciones.php',
  obtenerTipoDocumentos: 'obtenerTipoDocumentos.php',
  obtenerNotarias: 'obtenerNotarias.php',
  obtenerCondicionesDeclarantes: 'obtenerCondicionesDeclarantes.php',
  obtenerEstadosFichas: 'obtenerEstadosFichas.php',
  obtenerMantenimientos: 'obtenerMantenimientos.php',
  obtenerPersonasPorNombresApellidos: 'obtenerPersonasPorNombresApellidos.php',
  obtenerDeclarantesPorDni: 'obtenerDeclarantesPorDni.php',
  obtenerTipoUcas: 'obtenerTipoUcas.php',
  obtenerTiposEcs: 'obtenerTiposEcs.php',
  obtenerTiposEcc: 'obtenerTiposEcc.php',
  obtenerDepartamentos: 'obtenerDepartamentos.php',
  obtenerProvinciasSegunCodiDep: 'obtenerProvinciasSegunCodiDep.php',
  obtenerDistritosSegunCodiPro: 'obtenerDistritosSegunCodiPro.php',
  obtenerLotePorId: 'obtenerLotePorId.php',
  obtenerEdificacionPorId: 'obtenerEdificacionPorId.php',
};
